FROM eclipse-temurin:25-jdk

# Install curl and Maven 3.9.9
ENV MAVEN_VERSION=3.9.9
RUN apt-get update && apt-get install -y curl \
    && curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz | tar -xzC /opt \
    && ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/bin/mvn \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app

ENV JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS \
    -XshowSettings:vm \
    -Dquarkus.http.host=0.0.0.0 \
    -Dquarkus.profile=dev \
    -Dquarkus.analytics.disabled=true \
    -DdebugHost=0.0.0.0"

CMD mvn clean compile quarkus:dev