
FROM maven:3.9.9-amazoncorretto-21-al2023

WORKDIR /usr/app

ENV JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS \
    -XshowSettings:vm \
    -Dquarkus.http.host=0.0.0.0 \
    -Dquarkus.profile=dev \
    -Dquarkus.analytics.disabled=true \
    -DdebugHost=0.0.0.0"

CMD mvn clean compile quarkus:dev